/// Rust code emitter — generates azrs command modules from IR.
///
/// Emits:
/// - `<service>/<group>.rs` — command functions using ArmCommand
/// - `<service>/mod.rs` — module root
/// - CLI arg structs and dispatch match arms (printed to stdout for manual integration)
use crate::model::*;
use std::fmt::Write;
use std::path::Path;

/// Emit a complete service module to the output directory.
pub fn emit_service(module: &ServiceModule, output_dir: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(output_dir)?;

    // Emit mod.rs
    let mut mod_rs = String::new();
    writeln!(mod_rs, "// @generated by aaz-gen — do not edit").unwrap();
    writeln!(mod_rs, "// Source: azure-cli AAZ commands for service '{}'", module.name).unwrap();
    writeln!(mod_rs).unwrap();

    for group in &module.groups {
        let mod_name = sanitize_mod_name(&group.name);
        writeln!(mod_rs, "pub mod {mod_name};").unwrap();
    }

    std::fs::write(output_dir.join("mod.rs"), mod_rs)?;

    // Emit one file per group
    for group in &module.groups {
        let mod_name = sanitize_mod_name(&group.name);
        let content = emit_group(group);
        std::fs::write(output_dir.join(format!("{mod_name}.rs")), content)?;
    }

    // Emit CLI structs to stdout
    eprintln!("\n=== Generated CLI arg structs (paste into cli.rs) ===\n");
    eprint!("{}", emit_cli_structs(module));

    eprintln!("\n=== Generated dispatch arms (paste into main.rs) ===\n");
    eprint!("{}", emit_dispatch(module));

    Ok(())
}

/// Emit a single group file (e.g. asg.rs)
fn emit_group(group: &CommandGroup) -> String {
    let mut out = String::new();

    writeln!(out, "// @generated by aaz-gen — do not edit").unwrap();
    if let Some(ref help) = group.help {
        writeln!(out, "/// {help}").unwrap();
    }
    writeln!(out, "use crate::commands::ArmCommand;").unwrap();
    writeln!(out, "use crate::error::Result;").unwrap();
    writeln!(out).unwrap();

    for cmd in &group.commands {
        out.push_str(&emit_command(cmd));
        out.push('\n');
    }

    out
}

/// Emit a single command function.
fn emit_command(cmd: &CommandDef) -> String {
    let mut out = String::new();
    let fn_name = sanitize_fn_name(&cmd.verb);

    // Doc comment
    if let Some(ref help) = cmd.help {
        writeln!(out, "/// {help}").unwrap();
    }

    // Function signature
    let params = build_fn_params(cmd);
    let return_type = if cmd.operation.method == "DELETE" && !cmd.is_paged {
        "Result<()>"
    } else if cmd.is_paged || cmd.operation.method == "GET" && cmd.verb == "list" {
        "Result<Vec<serde_json::Value>>"
    } else {
        "Result<serde_json::Value>"
    };

    writeln!(out, "pub async fn {fn_name}({params}) -> {return_type} {{").unwrap();
    writeln!(out, "    let mut cmd = ArmCommand::new()?;").unwrap();

    // Build path
    let url = &cmd.operation.url_template;
    let api_version = &cmd.operation.api_version;

    // Replace ARM placeholders with Rust format args
    let mut rust_url = url.replace("{subscriptionId}", "{{subscriptionId}}");
    let mut format_args = Vec::new();

    // Map URL params to function params
    for arg in &cmd.args {
        let placeholder = url_placeholder_for_arg(&arg.name, url);
        if let Some(ph) = placeholder {
            rust_url = rust_url.replace(&format!("{{{ph}}}"), &format!("{{{}}}", arg.name));
            format_args.push(arg.name.clone());
        }
    }

    writeln!(
        out,
        "    let arm_url = format!(\"{rust_url}?api-version={api_version}\");"
    )
    .unwrap();

    // Emit the call
    let method = &cmd.operation.method;
    match method.as_str() {
        "GET" if cmd.verb == "list" || cmd.is_paged => {
            writeln!(out, "    let results = cmd.list(&arm_url).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(results)").unwrap();
        }
        "GET" => {
            writeln!(out, "    let result = cmd.get(&arm_url).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(result)").unwrap();
        }
        "PUT" if cmd.is_lro => {
            writeln!(out, "    let body = serde_json::json!({{}}); // TODO: populate body from args").unwrap();
            writeln!(out, "    let result = cmd.put_lro(&arm_url, &body).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(result)").unwrap();
        }
        "PUT" => {
            writeln!(out, "    let body = serde_json::json!({{}}); // TODO: populate body from args").unwrap();
            writeln!(out, "    let result = cmd.put(&arm_url, &body).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(result)").unwrap();
        }
        "DELETE" => {
            writeln!(out, "    cmd.delete(&arm_url).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
        }
        "POST" if cmd.is_lro => {
            writeln!(out, "    cmd.post_lro(&arm_url, None).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(())").unwrap();
        }
        "POST" => {
            writeln!(out, "    let result = cmd.post(&arm_url, None).await?;").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(result)").unwrap();
        }
        "PATCH" => {
            writeln!(out, "    let body = serde_json::json!({{}}); // TODO: populate body from args").unwrap();
            writeln!(out, "    let result = cmd.put(&arm_url, &body).await?; // PATCH via PUT").unwrap();
            writeln!(out, "    cmd.save_cache()?;").unwrap();
            writeln!(out, "    Ok(result)").unwrap();
        }
        _ => {
            writeln!(out, "    todo!(\"Unsupported method: {method}\")").unwrap();
        }
    }

    writeln!(out, "}}").unwrap();
    out
}

/// Emit clap arg structs for a service module.
pub fn emit_cli_structs(module: &ServiceModule) -> String {
    let mut out = String::new();
    let service_upper = capitalize(&module.name);

    writeln!(out, "// @generated — CLI arg structs for {}", module.name).unwrap();
    writeln!(out).unwrap();

    // Top-level service subcommand enum
    writeln!(out, "#[derive(Subcommand)]").unwrap();
    writeln!(out, "pub enum {service_upper}GenCommands {{").unwrap();
    for group in &module.groups {
        let group_upper = capitalize(&sanitize_mod_name(&group.name));
        let help = group.help.as_deref().unwrap_or("Manage resources");
        writeln!(out, "    /// {help}").unwrap();
        writeln!(out, "    #[command(subcommand)]").unwrap();
        writeln!(out, "    {group_upper}({service_upper}{group_upper}Commands),").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // Per-group subcommand enums
    for group in &module.groups {
        let group_upper = capitalize(&sanitize_mod_name(&group.name));
        writeln!(out, "#[derive(Subcommand)]").unwrap();
        writeln!(out, "pub enum {service_upper}{group_upper}Commands {{").unwrap();
        for cmd in &group.commands {
            let verb_upper = capitalize(&cmd.verb);
            let help = cmd.help.as_deref().unwrap_or(&cmd.verb);
            writeln!(out, "    /// {help}").unwrap();
            writeln!(out, "    {verb_upper}({service_upper}{group_upper}{verb_upper}Args),").unwrap();
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        // Per-command arg structs
        for cmd in &group.commands {
            let verb_upper = capitalize(&cmd.verb);
            writeln!(out, "#[derive(clap::Args)]").unwrap();
            writeln!(out, "pub struct {service_upper}{group_upper}{verb_upper}Args {{").unwrap();
            for arg in &cmd.args {
                let field = sanitize_field_name(&arg.name);
                let clap_type = arg.arg_type.clap_type();
                if let Some(ref help) = arg.help {
                    writeln!(out, "    /// {help}").unwrap();
                }
                let opts: Vec<String> = arg.options.iter().map(|o| format!("\"{o}\"")).collect();
                let _opts_str = opts.join(", ");

                if arg.required {
                    writeln!(out, "    #[arg(long, short = '{}')]", short_flag(&arg.options)).unwrap();
                } else {
                    writeln!(out, "    #[arg(long)]").unwrap();
                }

                if arg.required {
                    writeln!(out, "    pub {field}: {clap_type},").unwrap();
                } else {
                    writeln!(out, "    pub {field}: Option<{clap_type}>,").unwrap();
                }
            }
            writeln!(out, "}}").unwrap();
            writeln!(out).unwrap();
        }
    }

    out
}

/// Emit dispatch match arms for main.rs.
pub fn emit_dispatch(module: &ServiceModule) -> String {
    let mut out = String::new();
    let service_upper = capitalize(&module.name);

    writeln!(out, "// @generated — dispatch for {}", module.name).unwrap();

    for group in &module.groups {
        let group_upper = capitalize(&sanitize_mod_name(&group.name));
        let mod_name = sanitize_mod_name(&group.name);

        for cmd in &group.commands {
            let verb_upper = capitalize(&cmd.verb);
            let fn_name = sanitize_fn_name(&cmd.verb);
            let call_args: Vec<String> = cmd.args.iter().map(|a| {
                let field = sanitize_field_name(&a.name);
                if a.required {
                    format!("&args.{field}")
                } else {
                    format!("args.{field}.as_deref()")
                }
            }).collect();
            let args_str = call_args.join(", ");

            let wrapper = if cmd.operation.method == "DELETE" {
                "cmd_handlers::wrap_none"
            } else if cmd.verb == "list" || cmd.is_paged {
                "cmd_handlers::wrap_list"
            } else {
                "cmd_handlers::wrap"
            };

            writeln!(out, "// {service_upper}{group_upper}Commands::{verb_upper}(args) => {wrapper}(crate::generated::{mod_name}::{fn_name}({args_str}).await),").unwrap();
        }
    }

    out
}

// --- Helpers ---

/// Build function parameter list from command args.
fn build_fn_params(cmd: &CommandDef) -> String {
    cmd.args
        .iter()
        .filter(|a| {
            // Only include args that appear in the URL (path params)
            // Body args get a TODO comment instead
            url_placeholder_for_arg(&a.name, &cmd.operation.url_template).is_some()
        })
        .map(|a| {
            let name = sanitize_field_name(&a.name);
            format!("{name}: &str")
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn sanitize_mod_name(s: &str) -> String {
    s.replace('-', "_").replace(' ', "_").to_lowercase()
}

fn sanitize_fn_name(s: &str) -> String {
    let name = s.replace('-', "_").to_lowercase();
    match name.as_str() {
        "type" => "type_".to_string(),
        "move" => "move_".to_string(),
        "path" => "path_".to_string(),
        _ => name,
    }
}

fn sanitize_field_name(s: &str) -> String {
    let name = s.replace('-', "_").to_lowercase();
    match name.as_str() {
        "type" => "type_".to_string(),
        "move" => "move_".to_string(),
        "path" => "path_".to_string(),
        _ => name,
    }
}

fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(c) => {
            let mut r = c.to_uppercase().to_string();
            r.push_str(chars.as_str());
            r
        }
    }
}

/// Find a URL placeholder that matches an arg name.
/// e.g. arg "name" → "{applicationSecurityGroupName}" (heuristic: ends with Name or matches)
fn url_placeholder_for_arg(arg_name: &str, url: &str) -> Option<String> {
    let re = regex::Regex::new(r"\{(\w+)\}").unwrap();
    for cap in re.captures_iter(url) {
        let placeholder = cap.get(1).unwrap().as_str();
        if placeholder == "subscriptionId" {
            continue;
        }
        // Direct match
        if placeholder.to_lowercase() == arg_name.to_lowercase() {
            return Some(placeholder.to_string());
        }
        // resourceGroupName → resource_group
        if arg_name == "resource_group" && placeholder.to_lowercase().contains("resourcegroup") {
            return Some(placeholder.to_string());
        }
        // Last path segment name → name
        if arg_name == "name" && placeholder.to_lowercase().ends_with("name") && !placeholder.to_lowercase().contains("resourcegroup") {
            return Some(placeholder.to_string());
        }
    }
    None
}

fn short_flag(options: &[String]) -> char {
    for opt in options {
        if opt.starts_with('-') && !opt.starts_with("--") && opt.len() == 2 {
            return opt.chars().nth(1).unwrap_or('x');
        }
    }
    'x'
}
